### ISSUE TITLE
No Completion - No Project Files Found

### ISSUE THREAD

**Issue by olegbl** [emmetio/sublime-tern#22]
Issue:
It seems like the "include" setting only narrows the lsit of files scanned by tern, rather than expanding it. I would expect the "include" setting to actually add the directories specified to the list of directories scanned.

Details:
I prefer to keep my .sublime-project and .sublime-workspace files in their own, completely unrelated directories, rather than with the source code, in order to keep the repo space cleaner. Consequently, Tern is unable to find any files in my project (since they're in a completely different directory), and is unusable.

Here's my .sublime-project's ternjs section:
"ternjs":
    {
        "include": ["/Users/username/source/project1/subprojectA/**"],
        "libs": ["browser", "jquery"],
        "plugins": {
        }
    }

**Comment by zqjimlove** [comment]
i found a bug in controller.js ，fixed is ok！#50
